title: MedMod
description: Multimodal Benchmark for Medical Prediction Tasks with Electronic Health Records and Chest X-Ray Images
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  repository_name: "MedMod"
  repository_url: https://anonymous.4open.science/r/MedMod-727D/README.md
  paper_url: https://neurips2024.com/
  owner_name: "Neurips 2024"
  owner_url: https://neurips2024.com/